name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '14 2 * * *'

jobs:
  scheduled:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade requests
    - name: Fetch latest data
      run: |-
        python -u utils/scrape.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
