name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '14 2 * * *'

jobs:
  scheduled:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Fetch latest data
      run: |-
        curl -OJ 'https://naptan.api.dft.gov.uk/v1/{access-nodes?dataFormat=xml,access-nodes?dataFormat=csv,nptg,nptg/localities}'
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
